#!/bin/bash

#ddev-generated
## Description: Run pnpm in the web container
## Usage: pnpm
## Example: "ddev pnpm"
## ExecRaw: true
## HostWorkingDir: true

# If a $PNPM_DIRECTORY is set, run our PNPM commands in that directory
if [ -n "$PNPM_DIRECTORY" ]; then
  pnpm --dir "$PNPM_DIRECTORY" "$@"
else
  pnpm "$@"
fi
